---
# https://stackoverflow.com/a/46699211 NOT WORK ;-(
- name: Get info about {{ php_fpm_path_to_main_config_fact }} exist
  when: ansible_os_family == 'Suse'
  stat:
    path: "{{ php_fpm_path_to_main_config_fact }}"
  register: php_fpm_path_to_main_config_state

- name: Get info about {{ php_fpm_path_to_config_fact }} exist
  when: ansible_os_family == 'Suse'
  stat:
    path: "{{ php_fpm_path_to_config_fact }}"
  register: php_fpm_path_to_config_state

- name: Copy main php-fpm config from default 4 openSUSE
  when:
    - ansible_os_family == 'Suse'
    # - php_fpm_path_to_main_config_state.stat.exists == false
    - not (php_fpm_path_to_main_config_state.stat.exists)
  become: yes
  copy:
    src: /etc/php{{ dokuwiki_opensuse_php_major_version }}/fpm/php-fpm.conf.default
    dest: /etc/php{{ dokuwiki_opensuse_php_major_version }}/fpm/php-fpm.conf
    remote_src: yes

- name: Copy www php-fpm config from default 4 openSUSE
  when:
    - ansible_os_family == 'Suse'
    # - php_fpm_path_to_config_state.stat.exists == false
    - not (php_fpm_path_to_config_state.stat.exists)
  become: yes
  copy:
    src: '{{ php_fpm_path_to_config_fact }}.default'
    dest: '{{ php_fpm_path_to_config_fact }}'
    remote_src: yes

# https://www.vultr.com/docs/how-to-install-dokuwiki-on-fedora-28#Step_3___Install_DokuWiki
- name: Config php-fpm.d "user" option
  when: ansible_system == 'Linux'
  # https://stackoverflow.com/a/49127686
  # environment:
  #   LC_CTYPE: en_US.UTF-8
  become: yes
  ini_file:
    path: '{{ php_fpm_path_to_config_fact }}'
    section: www
    option: user
    value: "{{ dokuwiki_php_fpm_user }}"
    backup: yes
  register: php_fpm_config_user_dokuwiki_state

- name: Config php-fpm.d "group" option
  when: ansible_system == 'Linux'
  # environment:
  #   LC_CTYPE: en_US.UTF-8
  become: yes
  ini_file:
    path: '{{ php_fpm_path_to_config_fact }}'
    section: www
    option: group
    value: "{{ dokuwiki_php_fpm_group }}"
    backup: yes
  register: php_fpm_config_group_dokuwiki_state

- name: Config php-fpm.d "listen" option
  when: ansible_system == 'Linux'
  # environment:
  #   LC_CTYPE: en_US.UTF-8
  become: yes
  ini_file:
    path: '{{ php_fpm_path_to_config_fact }}'
    section: www
    option: listen
    value: "{{ dokuwiki_php_fpm_connection_address }}"
    backup: yes
  register: php_fpm_config_listen_dokuwiki_state

# https://serveradmin.ru/ustanovka-i-nastroyka-nginx-php-fpm-php7-1-na-centos-7/
- name: Config php-fpm.d "listen.owner" option
  when: ansible_system == 'Linux'
  # environment:
  #   LC_CTYPE: en_US.UTF-8
  become: yes
  ini_file:
    path: '{{ php_fpm_path_to_config_fact }}'
    section: www
    option: listen.owner
    value: "{{ dokuwiki_php_fpm_user }}"
    backup: yes
  register: php_fpm_config_listen_owner_dokuwiki_state

- name: Config php-fpm.d "listen.group" option
  when: ansible_system == 'Linux'
  # environment:
  #   LC_CTYPE: en_US.UTF-8
  become: yes
  ini_file:
    path: '{{ php_fpm_path_to_config_fact }}'
    section: www
    option: listen.group
    value: "{{ dokuwiki_php_fpm_group }}"
    backup: yes
  register: php_fpm_config_listen_group_dokuwiki_state

- name: Config php-fpm.d "listen.mode" option
  when: ansible_system == 'Linux'
  # environment:
  #   LC_CTYPE: en_US.UTF-8
  become: yes
  ini_file:
    path: '{{ php_fpm_path_to_config_fact }}'
    section: www
    option: listen.mode
    value: '0660'
    backup: yes
  register: php_fpm_config_listen_mode_dokuwiki_state

- name: Create directory structure 4 php-fpm.socket
  when:
    - ansible_system == 'Linux'
    - dokuwiki_php_fpm_connection_type == 'socket'
  become: yes
  file:
    path: '{{ php_fpm_path_to_directory_with_socket_fact }}'
    state: directory

- name: php-fpm restart
  when: 
    - ansible_system == 'Linux'
    - php_fpm_config_user_dokuwiki_state.changed
      or
      php_fpm_config_group_dokuwiki_state.changed
      or
      php_fpm_config_listen_dokuwiki_state.changed
      or
      php_fpm_config_listen_owner_dokuwiki_state.changed
      or
      php_fpm_config_listen_group_dokuwiki_state.changed
      or
      php_fpm_config_listen_mode_dokuwiki_state.changed
  become: yes
  service:
    name: '{{ php_fpm_service_name_fact }}'
    state: restarted

- name: Ensure php-fpm is running
  when: ansible_system == 'Linux'
  become: yes
  service:
    name: '{{ php_fpm_service_name_fact }}'
    state: started

- name: Chmod php-fpm socket
  when:
    - ansible_system == 'Linux'
    - dokuwiki_php_fpm_connection_type == 'socket'
  become: yes
  file:
    path: '{{ dokuwiki_php_fpm_connection_address }}'
    owner: '{{ dokuwiki_php_fpm_user }}'
    group: '{{ dokuwiki_php_fpm_group }}'
    # mode: '0660'
