---
- name: Configure Lighttpd config 4 DokuWiki
  when:
    - ansible_system == 'Linux'
  become: yes
  template:
    src: dokuwiki-lighttpd.j2
    dest: /etc/lighttpd/conf-available/80-{{ dokuwiki_web_server_config_name }}.conf
    backup: yes

# https://stackoverflow.com/a/26098212
- name: Enable DokuWiki site
  when:
    - ansible_pkg_mgr == 'apt'
  become: yes
  file:
    src: /etc/lighttpd/conf-available/80-{{ dokuwiki_web_server_config_name }}.conf
    dest: /etc/lighttpd/conf-enabled/80-{{ dokuwiki_web_server_config_name }}.conf
    state: link

- name: Enable FastCGI
  when:
    - ansible_pkg_mgr == 'apt'
  become: yes
  file:
    src: /etc/lighttpd/conf-available/10-fastcgi.conf
    dest: /etc/lighttpd/conf-enabled/10-fastcgi.conf
    state: link

- name: Enable FastCGI php
  when:
    - ansible_pkg_mgr == 'apt'
  become: yes
  file:
    src: /etc/lighttpd/conf-available/15-fastcgi-php.conf
    dest: /etc/lighttpd/conf-enabled/15-fastcgi-php.conf
    state: link

- name: Enable JavaScript support
  when:
    - ansible_pkg_mgr == 'apt'
  become: yes
  file:
    src: /etc/lighttpd/conf-available/90-javascript-alias.conf
    dest: /etc/lighttpd/conf-enabled/90-javascript-alias.conf
    state: link
  register: lighttpd_config_dokuwiki_state

- name: Config port
  when:
    - ansible_system == 'Linux'
  become: yes
  replace:
    path: /etc/lighttpd/lighttpd.conf
    regexp: "^server.port.*"
    replace: 'server.port                 = {{ dokuwiki_www_port }}'
    backup: yes
  tags:
    - www-port
