---
- name: Install NGINX
  when:
    - ansible_system == 'Linux'
  become: yes
  package:
    name:
      - nginx
      # - nginx-extras
      # # https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=851784#10
      # - nginx-full
    state: present

- name: Delete default config from "sites-enabled"
  when:
    - ansible_system == 'Linux'
  become: yes
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Configure NGINX config 4 DokuWiki
  when:
    - ansible_system == 'Linux'
  become: yes
  template:
    src: dokuwiki-nginx.j2
    dest: /etc/nginx/sites-available/80-{{ dokuwiki_web_server_config_name }}.conf
    mode: '644'
    backup: yes
    # validate: bash -c 'nginx -t -c /dev/stdin <<< "events {worker_connections 1;} http { include %s; }"'
  # https://stackoverflow.com/a/57572036
  register: nginx_config_dokuwiki_state

# https://stackoverflow.com/a/26098212
- name: Enable DokuWiki site
  when:
    - ansible_system == 'Linux'
  become: yes
  file:
    src: /etc/nginx/sites-available/80-{{ dokuwiki_web_server_config_name }}.conf
    dest: /etc/nginx/sites-enabled/80-{{ dokuwiki_web_server_config_name }}.conf
    state: link

- name: Enable and start NGINX service
  when:
    - ansible_system == 'Linux'
  become: yes
  service:
    name: nginx
    state: started
    enabled: yes
