---
- name: Disable 000-default.conf
  when:
    - ansible_pkg_mgr == 'dnf'
  become: yes
  file:
    path: /etc/httpd/conf.d/welcome.conf
    state: absent
 
- name: Configure Apache config 4 DokuWiki
  when:
    - ansible_pkg_mgr == 'dnf'
  become: yes
  template:
    src: dokuwiki-apache.j2
    dest: /etc/httpd/conf.d/080-{{ dokuwiki_web_server_config_name }}.conf
    mode: '644'
    backup: yes
  register: apache_config_dokuwiki_state

# https://www.dokuwiki.org/install:ubuntu#apache_configuration_for_running_dokuwiki_in_public_html
# In Fedora - modules are already present
- name: Enable Apache module userdir
  when:
    - ansible_distribution != 'Fedora'
    - ansible_pkg_mgr == 'dnf'
  become: yes
  apache2_module:
    name: userdir
    state: present

- name: Enable Apache module rewrite
  when:
    - ansible_distribution != 'Fedora'
    - ansible_pkg_mgr == 'dnf'
  become: yes
  apache2_module:
    name: rewrite
    state: present
