---
- name: Ensure php-fpm is running
  when:
    - ansible_os_family == 'RedHat'
  become: yes
  service:
    name: php-fpm
    state: started

# TODO. Когда доведу до рабочего состояния - рефакторнуть 's/replace/ini_file/'. https://docs.ansible.com/ansible/2.9/modules/ini_file_module.html

# https://www.vultr.com/docs/how-to-install-dokuwiki-on-fedora-28#Step_3___Install_DokuWiki
- name: Config php-fpm.d "user" option 4 CentOS 8+\RHEL
  when:
    - ansible_os_family == 'RedHat'
  become: yes
  replace:
    path: /etc/php-fpm.d/www.conf
    regexp: "^user = apache"
    replace: 'user = www-data'
    backup: yes

- name: Config php-fpm.d "group" option 4 CentOS 8+\RHEL
  when:
    - ansible_os_family == 'RedHat'
  become: yes
  replace:
    path: /etc/php-fpm.d/www.conf
    regexp: "^group = apache"
    replace: 'group = www-data'
    backup: yes

# https://serveradmin.ru/ustanovka-i-nastroyka-nginx-php-fpm-php7-1-na-centos-7/
- name: Config php-fpm.d "listen.owner" option 4 CentOS 8+\RHEL
  when:
    - ansible_os_family == 'RedHat'
  become: yes
  replace:
    path: /etc/php-fpm.d/www.conf
    regexp: "^;listen.owner = nobody"
    replace: 'listen.owner = www-data'
    backup: yes

- name: Config php-fpm.d "listen.group" option 4 CentOS 8+\RHEL
  when:
    - ansible_os_family == 'RedHat'
  become: yes
  replace:
    path: /etc/php-fpm.d/www.conf
    regexp: "^;listen.group = nobody"
    replace: 'listen.group = www-data'
    backup: yes

- name: Config php-fpm.d "listen.mode" option 4 CentOS 8+\RHEL
  when:
    - ansible_os_family == 'RedHat'
  become: yes
  replace:
    path: /etc/php-fpm.d/www.conf
    regexp: "^;listen.mode = 0660"
    replace: 'listen.mode = 0660'
    backup: yes
  register: php_fpm_dokuwiki_state

- name: php-fpm restart
  when:
    - ansible_os_family == 'RedHat'
    # - php_fpm_dokuwiki_state.changed == true
    - php_fpm_dokuwiki_state.changed
  become: yes
  service:
    name: php-fpm
    state: restarted

- name: Chmod php-fpm socket 4 CentOS 8+\RHEL
  when:
    - ansible_os_family == 'RedHat'
  become: yes
  file:
    path: '{{ php_fpm_path_to_socket }}'
    owner: www-data
    group: www-data
    # mode: '0660'
