---
# - name: Delete default config from "sites-enabled"
#   when:
#     - ansible_system == 'Linux'
#   become: yes
#   file:
#     path: /etc/nginx/sites-enabled/default
#     state: absent

- name: Configure NGINX config 4 DokuWiki
  when:
    - ansible_system == 'Linux'
  become: yes
  template:
    src: dokuwiki-nginx.j2
    dest: '{{ nginx_path_to_sites_enabled }}/80-{{ dokuwiki_web_server_config_name }}.conf'
    mode: '644'
    backup: yes
    # validate: bash -c 'nginx -t -c /dev/stdin <<< "events {worker_connections 1;} http { include %s; }"'
  # https://stackoverflow.com/a/57572036
  register: nginx_config_dokuwiki_state

# # https://stackoverflow.com/a/26098212
# - name: Enable DokuWiki site
#   when:
#     - ansible_system == 'Linux'
#   become: yes
#   file:
#     src: /etc/nginx/sites-available/80-{{ dokuwiki_web_server_config_name }}.conf
#     dest: /etc/nginx/sites-enabled/80-{{ dokuwiki_web_server_config_name }}.conf
#     state: link
