---
# - name: Delete default config from "sites-enabled"
#   when:
#     - ansible_system == 'Linux'
#   become: yes
#   file:
#     path: /etc/nginx/sites-enabled/default
#     state: absent

- name: Configure NGINX config 4 DokuWiki
  when:
    - ansible_system == 'Linux'
  become: yes
  template:
    src: dokuwiki-nginx.j2
    dest: '{{ nginx_path_to_sites_enabled }}/80-{{ dokuwiki_web_server_config_name }}.conf'
    mode: '644'
    backup: yes
    # validate: bash -c 'nginx -t -c /dev/stdin <<< "events {worker_connections 1;} http { include %s; }"'
  # https://stackoverflow.com/a/57572036
  register: nginx_config_dokuwiki_state

- name: Config user in nginx.conf 4 CentOS 8+\RHEL
  when:
    - ansible_os_family == 'RedHat'
  become: yes
  replace:
    path: /etc/nginx/nginx.conf
    regexp: "^user nginx"
    replace: 'user www-data'
    backup: yes
  # register: nginx_config_dokuwiki_state

# "blockinfile" not work for me. If you know how it work - send patch or open issue, please.
- name: Delete default site in nginx.conf 4 CentOS 8+\RHEL (FUCKING DIRTY HACK)
  when:
    - ansible_os_family == 'RedHat'
  become: yes
  lineinfile:
    path: /etc/nginx/nginx.conf
    line: "{{ item }}"
    state: absent
    backup: yes
  with_items:
    - '    server {'
    - '        listen       80 default_server;'
    - '        listen       [::]:80 default_server;'
    - '        server_name  _;'
    - '        root         /usr/share/nginx/html;'
    - '        # Load configuration files for the default server block.'
    - '        include /etc/nginx/default.d/*.conf;'
    - '        location / {'
    - '        }'
    - '        error_page 404 /404.html;'
    - '            location = /40x.html {'
    - '        }'
    - '        error_page 500 502 503 504 /50x.html;'
    - '            location = /50x.html {'
    - '        }'
    - '    }'
  register: nginx_remove_default_config_site_state

# # https://stackoverflow.com/a/26098212
# - name: Enable DokuWiki site
#   when:
#     - ansible_system == 'Linux'
#   become: yes
#   file:
#     src: /etc/nginx/sites-available/80-{{ dokuwiki_web_server_config_name }}.conf
#     dest: /etc/nginx/sites-enabled/80-{{ dokuwiki_web_server_config_name }}.conf
#     state: link
