---
# Лол, в Fedora надо создавать www-data руками. Очень дружелюбная ОС.
- name: Create www-data group
  when: ansible_system == 'Linux'
  become: yes
  group:
    name: www-data
    system: yes
    state: present

- name: Create www-data user
  when: ansible_system == 'Linux'
  become: yes
  user:
    name: www-data
    group: www-data
    home: /var/www
    create_home: yes
    shell: /usr/sbin/nologin
    state: present
    system: yes

- name: Add user "nginx" 2 "www-data" group
  when:
    - ansible_os_family == 'RedHat'
    - dokuwiki_web_server_name == 'nginx'
  become: yes
  user:
    name: nginx
    groups: www-data
    append: yes

# php-fpm работает от него, так что веб-сервер указывать смысла нет.
- name: Add user "apache" 2 "www-data" group
  when:
    - ansible_os_family == 'RedHat'
  become: yes
  user:
    name: apache
    groups: www-data
    append: yes
