---
# Лол, в Fedora надо создавать www-data руками. Очень дружелюбная ОС.
- name: Create groups 4 web
  when: ansible_system == 'Linux'
  become: yes
  group:
    name: "{{ item }}"
    system: yes
    state: present
  with_items:
    - '{{ dokuwiki_group_web_server }}'
    - '{{ dokuwiki_group_php_fpm }}'

- name: Create web user
  when: ansible_system == 'Linux'
  become: yes
  user:
    name: '{{ dokuwiki_user_web_server }}'
    group: '{{ dokuwiki_group_web_server }}'
    home: '{{ dokuwiki_home_web_server }}'
    create_home: yes
    shell: /usr/sbin/nologin
    state: present
    system: yes

- name: Add users 2 web group
  when:
    - ansible_os_family == 'RedHat'
  become: yes
  user:
    name: "{{ item }}"
    groups: www-data
    append: yes
  with_items:
    - apache
    - nginx
    - lighttpd
    # - root
    - '{{ dokuwiki_user_web_server }}'
    - '{{ dokuwiki_user_php_fpm }}'
