---
- name: Install Lighttpd
  when:
    - ansible_system == 'Linux'
  become: yes
  package:
    name:
      - lighttpd
    state: present

- name: Install JavaScript support 4 Lighttpd 4 Debian\Ubuntu
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
  become: yes
  package:
    name:
      - javascript-common
    state: present

- name: Enable and start lighttpd service
  when:
    - ansible_system == 'Linux'
  become: yes
  service:
    name: lighttpd
    state: started
    enabled: yes
