---
- name: Install Lighttpd
  when:
    - ansible_system == 'Linux'
  become: yes
  package:
    name:
      - lighttpd
    state: present

#--- Classic share ---#

- name: Allow access deb repo over http
  when:
    - ansible_system == 'Linux'
  become: yes
  template:
    src: 80-aptly-share.conf.lighttpd.j2
    dest: /etc/lighttpd/conf-available/80-aptly-share.conf
    mode: '644'
    backup: yes

- name: Config port
  when:
    - ansible_system == 'Linux'
  become: yes
  replace:
    path: /etc/lighttpd/lighttpd.conf
    regexp: "^server.port.*"
    replace: 'server.port                 = {{ aptly_www_port }}'
    backup: yes
  tags:
    - www-port

#--- Service run ---#

- name: Enable and start lighttpd service
  when:
    - ansible_system == 'Linux'
  become: yes
  service:
    name: lighttpd
    state: started
    enabled: yes
