---
- name: Install NGINX
  when:
    - ansible_system == 'Linux'
  become: yes
  package:
    name:
      - nginx
      # - nginx-extras
      # # https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=851784#10
      # - nginx-full
    state: present

- name: Enable and start NGINX service
  when:
    - ansible_system == 'Linux'
  become: yes
  service:
    name: nginx
    state: started
    enabled: yes
