---
- name: Disable install Apache
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
    - dokuwiki_web_server_name != 'apache'
  become: yes
  # NOT FUCKING WORK
  # dpkg_selections:
  #   name: apache2
  #   selection: hold
  # https://www.tecmint.com/disable-lock-blacklist-package-updates-ubuntu-debian-apt/
  environment:
    LANG: C
    LC_ALL: C
  command: apt-mark hold apache2
  register: apache_disable_install
  changed_when: ( 'apache2 set on hold.' in apache_disable_install.stdout )

# https://www.dokuwiki.org/requirements
- name: Install deps 4 DokuWiki 4 Debian based distro
  when:
    # # - ansible_distribution == 'Ubuntu'
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
    # - ansible_system == 'Linux'
  become: yes
  package:
    name:
      # 4 пакета ниже - минимальный набор при котором всё вроде бы пашет (ну логиниться могу, настройки менять могу, вот это всё).
      - php
      - php-fpm
      - php-xml
      - php-mbstring
      # Всё чё ниже - под вопрсом. Пакеты были указаны в старом руководстве. На сколько актуально щас - хзхзхз.
      - php-cli
      - php-cgi
      - php-zip
      # А эти подсмотрены у apt install dokuwiki на ubuntu 20.04
      - php-curl
      - php-geshi
      # - php-ldap
      # # - php-phpseclib
      # # - php-random-compat
      - fontconfig
      # # - fonts-droid-fallback
      # # - fonts-noto-mono
      # # - fonts-urw-base35
      # - ghostscript
      # # - gsfonts
      # - hicolor-icon-theme
      
      # Вынести в отдельную таску.
      - imagemagick

      - poppler-data
    state: present
    # install_recommends: yes

- name: Install deps 4 DokuWiki 4 Fedora\CentOS 8+\RHEL
  when:
    - ansible_os_family == 'RedHat'
    - ansible_pkg_mgr == 'dnf'
  become: yes
  package:
    name:
      - php
      - php-cli
      - php-fpm
      - php-gd
      - php-xml
      - php-zip
      - php-json
      - ImageMagick

- name: Install deps 4 DokuWiki 4 openSUSE
  when:
    - ansible_os_family == 'Suse'
    - ansible_pkg_mgr == 'zypper'
  become: yes
  package:
    name:
      - php{{ dokuwiki_opensuse_php_major_version }}
      - php{{ dokuwiki_opensuse_php_major_version }}-fpm
      - php{{ dokuwiki_opensuse_php_major_version }}-gd
      - php{{ dokuwiki_opensuse_php_major_version }}-xmlreader
      - php{{ dokuwiki_opensuse_php_major_version }}-zip
      - php{{ dokuwiki_opensuse_php_major_version }}-json
      - php{{ dokuwiki_opensuse_php_major_version }}-mbstring
      - ImageMagick

# TODO. May be.
# sudo systemctl enable php-fpm.service


- name: Get installed status php
  when: ansible_system == 'Linux'
  become: yes
  block:
    - package_facts:
    # Превращаем "1:7.2+60ubuntu1" в "7.2". Если на bash: LC_ALL=C aptitude show php | grep ^Version | awk '{print $2}' | cut -d ':' -f 2 | cut -d '+' -f 1
    - set_fact:
        php_installed_version_fact: "{{ ansible_facts.packages['php'][0].version.split(':')[1].split('+')[0] }}"
      when:
        - ansible_os_family == 'Debian'
        - ansible_pkg_mgr == 'apt'
    - set_fact:
        php_installed_version_fact: "{{ ansible_facts.packages['php'][0].version.split('.', 2)[:-1] | join('.') }}"
      when:
        - ansible_os_family == 'RedHat'
        - ansible_pkg_mgr == 'dnf'
    - set_fact:
        php_installed_version_fact: "{{ ansible_facts.packages['php7'][0].version.split('.', 2)[:-1] | join('.') }}"
      when:
        - ansible_os_family == 'Suse'
        - ansible_pkg_mgr == 'zypper'

# # 4 debug
# - copy:
#     dest: /tmp/package_facts.json
#     content: "{{ ansible_facts.packages }}"
# - pause:
