---
# https://www.osradar.com/how-to-install-lighttpd-almalinux-centos/
- name: Install Lighttpd
  when:
    - ansible_os_family == 'RedHat'
    # - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == '8'
  become: yes
  package:
    name:
      - epel-release
    state: present

- name: Install Lighttpd
  when:
    - ansible_system == 'Linux'
  become: yes
  package:
    name:
      - lighttpd
    state: present

- name: Install Lighttpd FastCGI support
  when:
    - ansible_os_family == 'RedHat'
  become: yes
  package:
    name:
      - lighttpd-fastcgi
    state: present

- name: Install JavaScript support 4 Lighttpd 4 Debian\Ubuntu
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
  become: yes
  package:
    name:
      - javascript-common
    state: present

- name: Enable and start lighttpd service
  when:
    - ansible_system == 'Linux'
  become: yes
  service:
    name: lighttpd
    state: started
    enabled: yes
