---
- name: Install Apache 4 Debian\Ubuntu
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
  become: yes
  package:
    name:
      - apache2
    state: present

- name: Install Apache 4 CentOS 8+\RHEL
  when:
    - ansible_os_family == 'RedHat'
    - ansible_pkg_mgr == 'dnf'
  become: yes
  package:
    name:
      - httpd
    state: present
