---
- name: Create directory structure 4 plugins
  when: ansible_system == 'Linux'
  become: yes
  file:
    path: '{{ dokuwiki_fs_dir }}/lib/plugins/{{ item.dokuwiki_plugin_dir_name }}'
    owner: '{{ dokuwiki_user_web_server }}'
    group: '{{ dokuwiki_group_web_server }}'
    mode: '{{ dokuwiki_chmod }}'
    state: directory
  with_items:
    - "{{ dokuwiki_plugin_collection }}"

- name: Install plugins 4 DokuWiki
  when: ansible_system == 'Linux'
  become: yes
  unarchive:
    src: '{{ item.dokuwiki_plugin_url }}'
    dest: '{{ dokuwiki_fs_dir }}/lib/plugins/{{ item.dokuwiki_plugin_dir_name }}'
    remote_src: yes
    owner: '{{ dokuwiki_user_web_server }}'
    group: '{{ dokuwiki_group_web_server }}'
    mode: '{{ dokuwiki_chmod }}'
    extra_opts:
      - --strip-components={{ item.dokuwiki_plugin_skip_directory_level }}
  with_items:
    - "{{ dokuwiki_plugin_collection }}"

# https://www.dokuwiki.org/plugin:discussion
