---
- set_fact:
    # /run/php-fpm/
    php_fpm_path_to_directory_with_socket_fact: "{{ dokuwiki_php_fpm_connection_address | dirname }}"
  when:
    - ansible_system == 'Linux'

- set_fact:
    apache_service_name_fact: apache2.service
    apache_path_to_sites_available: /etc/apache2/sites-available
    apache_path_to_sites_enabled: /etc/apache2/sites-enabled

    lighttpd_path_to_sites_available: /etc/lighttpd/sites-available
    lighttpd_path_to_sites_enabled: /etc/lighttpd/sites-enabled

    nginx_path_to_sites_available: /etc/nginx/sites-available
    nginx_path_to_sites_enabled: /etc/nginx/sites-enabled

    php_fpm_path_to_config_fact: /etc/php/{{ php_installed_version_fact }}/fpm/pool.d/www.conf
    php_fpm_service_name_fact: php{{ php_installed_version_fact }}-fpm.service
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'

- set_fact:
    apache_service_name_fact: httpd.service
    apache_path_to_sites_available: /etc/httpd/conf.d
    apache_path_to_sites_enabled: /etc/httpd/conf.d

    lighttpd_path_to_sites_available: /etc/lighttpd/conf.d
    lighttpd_path_to_sites_enabled: /etc/lighttpd/conf.d

    nginx_path_to_sites_available: /etc/nginx/conf.d
    nginx_path_to_sites_enabled: /etc/nginx/conf.d

    php_fpm_path_to_config_fact: /etc/php-fpm.d/www.conf
    php_fpm_service_name_fact: php-fpm.service
  when:
    - ansible_os_family == 'RedHat'
    - ansible_pkg_mgr == 'dnf'

- set_fact:
    apache_service_name_fact: apache2.service
    # apache_path_to_sites_available: /etc/httpd/conf.d
    # apache_path_to_sites_enabled: /etc/httpd/conf.d
    apache_path_to_sites_available: /etc/apache2/vhosts.d
    apache_path_to_sites_enabled: /etc/apache2/vhosts.d

    lighttpd_path_to_sites_available: /etc/lighttpd/conf.d
    lighttpd_path_to_sites_enabled: /etc/lighttpd/conf.d

    nginx_path_to_sites_available: /etc/nginx/conf.d
    nginx_path_to_sites_enabled: /etc/nginx/conf.d

    php_fpm_path_to_main_config_fact: /etc/php{{ dokuwiki_opensuse_php_major_version }}/fpm/php-fpm.conf
    php_fpm_path_to_config_fact: /etc/php{{ dokuwiki_opensuse_php_major_version }}/fpm/php-fpm.d/www.conf
    php_fpm_service_name_fact: php-fpm.service
  when:
    - ansible_os_family == 'Suse'
    - ansible_pkg_mgr == 'zypper'

# 4 debug
# - debug:
#     msg: "{{ php_fpm_path_to_config_fact }}"
# - pause:
